package pl.wedding.management.model.reservation;

public enum Occasion {
    WEDDING, FUNERAL, BAPTISM, COMMUNION, CONFERENCE, DIVORCE_PARTY, UMBILICAL_PARTY, COMPANY_PARTY,
    BACHELOR_PARTY, BACHELORETTE_PARTY, GALA, JUBILEE;
}
